[project]
name = "xducs-datavis24"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "pandas>=2.2.3",
    "pymongo>=4.9.2",
    "pymongoarrow>=1.6.0",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
