[project]
name = "xducs-datavis24"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "pandas>=2.2.3",
    "sqlalchemy>=2.0.35",
]

[tool.uv]
dev-dependencies = []
